"""add avatar_base64 to User

Revision ID: 35104613c48b
Revises: deb6268d2d5c
Create Date: 2026-02-26 02:58:48.640975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35104613c48b'
down_revision = 'deb6268d2d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palayan_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_solenoid_open', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_solenoid_duration_sec', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palayan_config', schema=None) as batch_op:
        batch_op.drop_column('last_solenoid_duration_sec')
        batch_op.drop_column('last_solenoid_open')

    # ### end Alembic commands ###
