"""add last_solenoid_open_at to palayan_config

Revision ID: ac036cb559bf
Revises: d9a690920728
Create Date: 2026-02-26 19:31:58.368897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac036cb559bf'
down_revision = 'd9a690920728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palayan_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_solenoid_open_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('palayan_config', schema=None) as batch_op:
        batch_op.drop_column('last_solenoid_open_at')

    # ### end Alembic commands ###
